package main.java.enumeracao;

public enum SubSetorComercio {
	
	ALIMENTICIO, BELEZA, CONSTRUCAO, CULTURA, ELETRO_ELETRONICO, LAZER, LIMPEZA, MOBILIARIO, ORNAMENTACAO, OUTRO, PET, SAUDE, TRANSPORTE, VESTUARIO

}
