package main.java.enumeracao;

public enum SubSetorManutencao {
	
	ARTESANATO, AUTOMOVEL, BICICLETA, BRINQUEDO, CUSTOMIZACAO, ELETRO_ELETRONICO, FUNILARIA, 
	HIDRAULICA, INFORMATICA, INSTRUMENTO_MUSICAI, MAQUINA_PESADA, MARCENARIA, MOTOCICLETA,
	OUTRO, RELOJOARIA, SERRALHERIA, TELEFONIA
	
}
